# SPDX-License-Identifier: GPL-3.0-only

# Name of the application's binary.
name := 'pocket'
# The unique ID of the application.
appid := 'com.magnetaros.Pocket'

# Path to root file system, which defaults to `/`.
rootdir := ''
# The prefix for the `/usr` directory.
prefix := '/usr'
# The location of the cargo target directory. build.rs writes the generated
# XDG files under the same root, so redirecting it keeps everything together.
cargo-target-dir := env('CARGO_TARGET_DIR', 'target')

# Sources. The desktop entry and metainfo are GENERATED by build.rs from the
# templates in `resources/` plus the Fluent catalogues in `i18n/`, so the files
# installed below only exist after a build. `install` depends on that.
desktop-src := cargo-target-dir / 'xdgen' / 'app.desktop'
metainfo-src := cargo-target-dir / 'xdgen' / 'app.metainfo.xml'
icon-dir := 'resources' / 'icons' / 'hicolor'
icon-src := icon-dir / 'scalable' / 'apps' / (appid + '.svg')
icon-symbolic-src := icon-dir / 'symbolic' / 'apps' / (appid + '-symbolic.svg')
# The scalable SVG is what modern toolkits pick up; the PNGs are rasterised
# from it at each size so the panel and the icon grid get pixel-exact art
# instead of a downscaled smudge.
icon-sizes := '16x16 24x24 32x32 48x48 64x64 128x128 256x256 512x512'

# Install destinations
base-dir := absolute_path(clean(rootdir / prefix))
bin-dst := base-dir / 'bin' / name
desktop-dst := base-dir / 'share' / 'applications' / (appid + '.desktop')
metainfo-dst := base-dir / 'share' / 'metainfo' / (appid + '.metainfo.xml')
icons-dst := base-dir / 'share' / 'icons' / 'hicolor'
icon-dst := icons-dst / 'scalable' / 'apps' / (appid + '.svg')
icon-symbolic-dst := icons-dst / 'symbolic' / 'apps' / (appid + '-symbolic.svg')

# Default recipe which runs `just build-release`
default: build-release

# Everything CI runs, in the order that fails cheapest first.
check-all: fmt-check check test validate-metadata

# Runs `cargo clean`
clean:
    cargo clean

# Removes vendored dependencies
clean-vendor:
    rm -rf .cargo vendor vendor.tar

# `cargo clean` and removes vendored dependencies
clean-dist: clean clean-vendor

# Compiles with debug profile
build-debug *args:
    cargo build --locked {{args}}

# Compiles with release profile
build-release *args: (build-debug '--release' args)

# Compiles release profile with vendored dependencies
build-vendored *args: vendor-extract (build-release '--frozen --offline' args)

# Runs a clippy check
check *args:
    cargo clippy --all-features --all-targets {{args}} -- -D warnings

# Runs a clippy check with JSON message format
check-json: (check '--message-format=json')

# Checks formatting without changing anything.
fmt-check:
    cargo fmt --all -- --check

# Formats the source.
fmt:
    cargo fmt --all

# Runs the test suite
test *args:
    cargo test --workspace {{args}}

# Validates the GENERATED desktop entry and AppStream metadata.
#
# Deliberately validates the build output rather than the templates: the
# templates are not themselves valid installable files once xdgen is in the
# picture, and it is the generated pair that ends up on a user's disk.
validate-metadata: build-debug
    desktop-file-validate {{desktop-src}}
    appstreamcli validate --no-net {{metainfo-src}}

# Run the application for testing purposes
run *args:
    env RUST_BACKTRACE=full cargo run --release {{args}}

# Run against scratch passes, leaving the real wallet alone.
run-sandboxed dir='/tmp/pocket-passes': build-release
    mkdir -p {{dir}}
    env POCKET_PASS_DIR={{dir}} RUST_BACKTRACE=full {{ cargo-target-dir / 'release' / name }}

# Installs files, then refreshes the two caches that will not notice a new
# file on their own — "Open With" reads the first, the icon grid the second.
# Skipped when staging into a rootdir: the packager's postinst owns that.
install: build-release
    install -Dm0755 {{ cargo-target-dir / 'release' / name }} {{bin-dst}}
    install -Dm0644 {{desktop-src}} {{desktop-dst}}
    install -Dm0644 {{metainfo-src}} {{metainfo-dst}}
    install -Dm0644 {{icon-src}} {{icon-dst}}
    install -Dm0644 {{icon-symbolic-src}} {{icon-symbolic-dst}}
    for size in {{icon-sizes}}; do \
        install -Dm0644 {{icon-dir}}/$size/apps/{{appid}}.png \
            {{icons-dst}}/$size/apps/{{appid}}.png; \
    done
    if [ -z '{{rootdir}}' ]; then \
        update-desktop-database {{ base-dir / 'share' / 'applications' }} || true; \
        gtk-update-icon-cache -f -t {{ base-dir / 'share' / 'icons' / 'hicolor' }} || true; \
    fi

# Uninstalls installed files
uninstall:
    rm -f {{bin-dst}} {{desktop-dst}} {{metainfo-dst}} {{icon-dst}} {{icon-symbolic-dst}}
    for size in {{icon-sizes}}; do \
        rm -f {{icons-dst}}/$size/apps/{{appid}}.png; \
    done

# Vendor dependencies locally
vendor:
    mkdir -p .cargo
    cargo vendor | head -n -1 > .cargo/config.toml
    echo 'directory = "vendor"' >> .cargo/config.toml
    tar pcf vendor.tar vendor
    rm -rf vendor

# Extracts vendored dependencies
vendor-extract:
    rm -rf vendor
    tar pxf vendor.tar
